"use strict";
exports.__esModule = true;
var Alunos_1 = require("./Alunos");
var Professor_1 = require("./Professor");
console.log("----------------------------------");
var a;
a = new Alunos_1.Aluno();
a.setNumRegistro(1235);
a.setNome("Matheus Matiusch");
a.setEmail("Mat@tiuschcorp.com");
a.setTelefone("+55 11 12345-6789");
a.setCurso("Dev. Web JJ ");
a.setAnoMatricula(2019);
console.log(a);
console.log("----------------------------------");
var d;
d = new Professor_1.Professor();
d.setNumRegistro(4005);
d.setNome("Adrian Boladão");
d.setEmail("adr@adrcorp.com");
d.setTelefone("+55 11 94578-9778");
d.setValorHora(500);
d.setNumHora(150);
d.setAreaFormacao("Mito Da Computação");
console.log(d);
